### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by fernandomoraangel** [DDMAL/libmei#115]
I has tried to use libmei (in Windwos 10)  following the instructions in "Installing the Python bindings" but did not work. Is it necesary to compilate or somethng different? Thanks a lot for for your help.

**Comment by ClaireLouboutin** [comment]
Hello,
I have the exact same problem. Did you find a solution in the end ? Maybe another library usable for windows 10 that allows to manipulate MEI files ?

**Comment by ahankinson** [comment]
I don't have access to Windows to test it with. You could try this fork to see if it helps.

https://github.com/annplaksin/libmei

**Comment by ClaireLouboutin** [comment]
Thank you for your message ! Unfortunately, this does not work, it has not been made for windows users and I cannot install homebrew either... Do you know any other python library to manipulate MEI files ?
