### ISSUE TITLE
parseschema2.py generates build errors due to trailing comma in langs/cplusplus.py

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/libmei#75]
https://github.com/DDMAL/libmei/blob/master/tools/langs/cplusplus.py#L103.

If {onlyMixins} is empty, the comma in L103 (`MeiElement(other),`) remains and XCode throws an error, expecting an object to follow it.

**Comment by ahankinson** [comment]
Is this still a problem?

**Comment by ahwitz** [comment]
I haven't the foggiest, yet I haven't run into it.

**Comment by ifkarp** [comment]
Made some rearrangements to fix potential problems with this in commit f6df3bcc25f41ae2815632d987380059f79039a8

If you have any examples that would cause {onlyMixins} to be empty, please let me know so I can further test it
