### ISSUE TITLE
Add documentation to Installing and Compiling regarding how to find mei.framework

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/libmei#86]

**Comment by wabain** [comment]
I did add a bit for this (adapted from the Python page):

> After compiling you should put the resulting mei.framework folder in your /Library/Frameworks folder so that it can be found by other software. You can find the products of your build by going to the Organizer (top-right corner), selecting your project, and clicking the arrow next to "Derived Data." Your compiled framework will be a folder in the Build directory, depending on what you built it for (Debug or Release).
